---
title: "Project1"
author: "Coco Donovan"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(fpp2)
library(fpp3)
```

# Data Importing and Indexing

```{r}
data_start_ind <- 1
data_end_ind <- 1622
forecast_stary_ind <- 1623
forecast_end_ind <- 1722

# Read the specified sheet from the Excel file
s05 <- read_excel('Data Set for Class.xlsx', sheet = 'S05', skip = 2)

s05$Var02[s05$SeriesInd >= 43022 ] <- NA
s05$Var03[s05$SeriesInd >= 43022 ] <- NA

head(s05)
```

# Data Visualization

```{r}
var2_plot <- ggplot(s05, aes(x = SeriesInd, y = Var02)) +
  geom_point(color = "blue") +
  labs(title = "Plot of Var02 vs Series Index", x = "Series Index", y = "Value") +
  theme_minimal()
```

```{r}
var3_plot <- ggplot(s05, aes(x = SeriesInd, y = Var03)) +
  geom_point(color = "orange") +
  labs(title = "Plot of Var03 vs Series Index", x = "Series Index", y = "Value") +
  theme_minimal()
```

```{r}
grid.arrange(var2_plot, var3_plot, nrow = 2)
```

# Data Imputation 
I'm using linear imputation, so creating a line of best fit between the last two known points and filling in missing values along that line

```{r}
data_range <- which(s05$SeriesInd < 43022)
```

Values to forecast: 43022 - 43221
index numbers: 1623 - 1762

# Checking for Stationarity

```{r stationarity}
acf_var2 <- acf(s05$Var02[data_range], plot = FALSE)
acf_var3 <- acf(s05$Var03[data_range], plot = FALSE)

acf_var2_df <- data.frame(lag = acf_var2$lag, acf = acf_var2$acf)
acf_var3_df <- data.frame(lag = acf_var3$lag, acf = acf_var3$acf)

acf1 <- ggplot(acf_var2_df, aes(x = lag, y = acf)) +
  geom_bar(stat = "identity") +
  labs(title = "ACF of Var02", y = 'ACF')

acf2 <- ggplot(acf_var3_df, aes(x = lag, y = acf)) +
  geom_bar(stat = "identity") +
  labs(title = "ACF of Var03", y = 'ACF')

grid.arrange(acf1, acf2, nrow=2)
```

```{r pacf2}
pacf_var2 <- pacf(s05$Var02[data_range], plot = FALSE)
pacf_var3 <- pacf(s05$Var03[data_range], plot = FALSE)

pacf_var2_df <- data.frame(lag = pacf_var2$lag, pacf = pacf_var2$acf)
pacf_var3_df <- data.frame(lag = pacf_var3$lag, pacf = pacf_var3$acf)

pacf1 <- ggplot(pacf_var2_df, aes(x = lag, y = pacf)) +
  geom_bar(stat = "identity") +
  labs(title = "PACF of Var02", y = 'Partial ACF')

pacf2 <- ggplot(pacf_var3_df, aes(x = lag, y = pacf)) +
  geom_bar(stat = "identity") +
  labs(title = "PACF of Var03", y = 'Partial ACF')

grid.arrange(pacf1, pacf2, nrow=2)
```
The data is non-stationary.
We will preforming differencing to make the data stationary.

```{r}
v2 = s05$Var02[data_range] %>% tsclean()
v3 = s05$Var03[data_range] %>% tsclean()

var2_diff <- diff(v2, differences = 1)
var3_diff <- diff(v3, differences = 1)

var2_diff_df <- data.frame(Index = seq_along(var2_diff), Value = var2_diff)
var3_diff_df <- data.frame(Index = seq_along(var3_diff), Value = var3_diff)
```

```{r}
var2_plot <- ggplot(var2_diff_df, aes(x = Index, y = Value)) +
  geom_point(color = "blue") +
  labs(title = "Plot of Var02 differenced vs Index", x = "Index", y = "Value") +
  theme_minimal()
```

```{r}
var3_plot <- ggplot(var3_diff_df, aes(x = Index, y = Value)) +
  geom_point(color = "orange") +
  labs(title = "Plot of Var03 differenced vs Index", x = "Index", y = "Value") +
  theme_minimal()
```

```{r}
grid.arrange(var2_plot, var3_plot, nrow = 2)
```

```{r stationarity_diff}
acf_var2 <- acf(var2_diff, plot = FALSE)
acf_var3 <- acf(var3_diff, plot = FALSE)

acf_var2_df <- data.frame(lag = acf_var2$lag, acf = acf_var2$acf)
acf_var3_df <- data.frame(lag = acf_var3$lag, acf = acf_var3$acf)

acf1 <- ggplot(acf_var2_df, aes(x = lag, y = acf)) +
  geom_bar(stat = "identity") +
  labs(title = "ACF of Var02", y = 'ACF')

acf2 <- ggplot(acf_var3_df, aes(x = lag, y = acf)) +
  geom_bar(stat = "identity") +
  labs(title = "ACF of Var03", y = 'ACF')

grid.arrange(acf1, acf2, nrow=2)
```

```{r pacf}
pacf_var2 <- pacf(var2_diff, plot = FALSE)
pacf_var3 <- pacf(var3_diff, plot = FALSE)

pacf_var2_df <- data.frame(lag = pacf_var2$lag, pacf = pacf_var2$acf)
pacf_var3_df <- data.frame(lag = pacf_var3$lag, pacf = pacf_var3$acf)

pacf1 <- ggplot(pacf_var2_df, aes(x = lag, y = pacf)) +
  geom_bar(stat = "identity") +
  labs(title = "PACF of Var02", y = 'Partial ACF')

pacf2 <- ggplot(pacf_var3_df, aes(x = lag, y = pacf)) +
  geom_bar(stat = "identity") +
  labs(title = "PACF of Var03", y = 'Partial ACF')

grid.arrange(pacf1, pacf2, nrow=2)
```


```{r}
var2_aa = auto.arima(var2_diff)
summary(var2_aa)
checkresiduals(var2_aa)

fc_var2 <- forecast(var2_aa, h=100)
autoplot(fc_var2)

var2 = s04$Var02

# Fit the ARIMA model to the differenced data
fit2 <- Arima(var2_diff, order = c(2, 1, 3), include.drift = TRUE)

# Forecast the differenced series
fc2 <- forecast(fit2, h = 140)

forecast_var2_df = data.frame(fc2$mean, fc2$upper[, 1], fc2$lower[, 1], fc2$upper[, 2], fc2$lower[, 2])

forecast_var2_df

forecast_var2_df = forecast_var2_df %>%
  mutate(Time = row_number() + 1622) %>%
  rename(ci_80_upper = fc2.upper...1.,
         ci_80_lower = fc2.lower...1.,
         ci_95_upper = fc2.upper...2.,
         ci_95_lower = fc2.lower...2.,
         forecast = fc2.mean) %>%
  select(Time, forecast, ci_80_lower, ci_80_upper, ci_95_lower, ci_95_upper)

df = forecast_var2_df
```


```{r}
# Get the last observed value of the original series
last_value <- tail(s04$Var02[data_range], 1)

last_value

# Create a new forecast column based on the given logic
new_forecast <- numeric(nrow(df))
new_forecast[1] <- df$forecast[1] + last_value

for (i in 2:nrow(df)) {
  new_forecast[i] <- new_forecast[i - 1] + df$forecast[i]
}

new_forecast

# Update the confidence intervals
new_ci_80_lower <- df$ci_80_lower + new_forecast
new_ci_80_upper <- df$ci_80_upper + new_forecast
new_ci_95_lower <- df$ci_95_lower + new_forecast
new_ci_95_upper <- df$ci_95_upper + new_forecast

# Create the new dataframe
new_df <- data.frame(
  Time = df$Time,
  Value = NA,
  forecast = new_forecast,
  ci_80_lower = new_ci_80_lower,
  ci_80_upper = new_ci_80_upper,
  ci_95_lower = new_ci_95_lower,
  ci_95_upper = new_ci_95_upper
)

original_vals = s04 %>%
  slice(1:1622) %>%
  select(Var02) %>%
  rename(Value = Var02) %>%
  mutate(Time = row_number(), 
         forecast = NA,
         ci_80_lower = NA,
         ci_80_upper = NA,
         ci_95_lower = NA,
         ci_95_upper = NA) %>%
  select(Time, Value, forecast, ci_80_lower, ci_80_upper, ci_95_lower, ci_95_upper)

full_df = rbind(original_vals, new_df)

full_df %>% slice(1500:1670)

# Plot the original series and the forecast with confidence intervals
ggplot(full_df, aes(x = Time)) +
  geom_line(aes(y = Value), color = 'black') +
  geom_line(aes(y = forecast), color = 'blue') +
  geom_ribbon(aes(ymin = ci_80_lower, ymax = ci_80_upper), fill = 'dodgerblue', alpha = 0.3) +
  geom_ribbon(aes(ymin = ci_95_lower, ymax = ci_95_upper), fill = 'dodgerblue4', alpha = 0.3) +
  labs(title = 'Var02 Forecasts using ARIMA(2,1,3) with drift',
       x = 'Time', y = 'Value') +
  theme_minimal()
```


```{r}
var3_aa = auto.arima(var3_diff)
summary(var3_aa)
checkresiduals(var3_aa)
```


```{r}
fc_var3 <- forecast(var3_aa, h=100)
autoplot(fc_var3)

# Fit the ARIMA model to the differenced data
fit3 <- Arima(var3_diff, order = c(2, 1, 3), include.drift = TRUE)

# Forecast the differenced series
fc3 <- forecast(fit3, h = 140)

forecast_var3_df = data.frame(fc3$mean, fc3$upper[, 1], fc3$lower[, 1], fc3$upper[, 2], fc3$lower[, 2])

forecast_var3_df

forecast_var3_df = forecast_var3_df %>%
  mutate(Time = row_number() + 1622) %>%
  rename(ci_80_upper = fc3.upper...1.,
         ci_80_lower = fc3.lower...1.,
         ci_95_upper = fc3.upper...2.,
         ci_95_lower = fc3.lower...2.,
         forecast = fc3.mean) %>%
  select(Time, forecast, ci_80_lower, ci_80_upper, ci_95_lower, ci_95_upper)

df = forecast_var3_df

df
```


```{r}
# Get the last observed value of the original series
last_value <- tail(s05$Var03[data_range], 1)

last_value

# Create a new forecast column based on the given logic
new_forecast <- numeric(nrow(df))
new_forecast[1] <- df$forecast[1] + last_value

for (i in 2:nrow(df)) {
  new_forecast[i] <- new_forecast[i - 1] + df$forecast[i]
}

new_forecast

# Update the confidence intervals
new_ci_80_lower <- df$ci_80_lower + new_forecast
new_ci_80_upper <- df$ci_80_upper + new_forecast
new_ci_95_lower <- df$ci_95_lower + new_forecast
new_ci_95_upper <- df$ci_95_upper + new_forecast

# Create the new dataframe
new_df <- data.frame(
  Time = df$Time,
  Value = NA,
  forecast = new_forecast,
  ci_80_lower = new_ci_80_lower,
  ci_80_upper = new_ci_80_upper,
  ci_95_lower = new_ci_95_lower,
  ci_95_upper = new_ci_95_upper
)

original_vals = s05 %>%
  slice(1:1622) %>%
  select(Var03) %>%
  rename(Value = Var03) %>%
  mutate(Time = row_number(), 
         forecast = NA,
         ci_80_lower = NA,
         ci_80_upper = NA,
         ci_95_lower = NA,
         ci_95_upper = NA) %>%
  select(Time, Value, forecast, ci_80_lower, ci_80_upper, ci_95_lower, ci_95_upper)

full_df = rbind(original_vals, new_df)

full_df %>% slice(1500:1670)

# Plot the original series and the forecast with confidence intervals
ggplot(full_df, aes(x = Time)) +
  geom_line(aes(y = Value), color = 'black') +
  geom_line(aes(y = forecast), color = 'blue') +
  geom_ribbon(aes(ymin = ci_80_lower, ymax = ci_80_upper), fill = 'dodgerblue', alpha = 0.3) +
  geom_ribbon(aes(ymin = ci_95_lower, ymax = ci_95_upper), fill = 'dodgerblue4', alpha = 0.3) +
  labs(title = 'Var03 Forecasts using ARIMA(2,1,3) with drift',
       x = 'Time', y = 'Value') +
  theme_minimal()
```

