---
title: "Project1"
author: "Brandon Cunningham"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(fpp2)
library(fpp3)
```

#Data Importing and Indexing

```{r}
data_start_ind <- 1
data_end_ind <- 1622
forecast_stary_ind <- 1623
forecast_end_ind <- 1722

path <- 'dataset.xls'
sheet_name <- 'S03'

# Read the specified sheet from the Excel file
s03 <- read_excel(path, sheet = sheet_name)
```

#Data Visualization

```{r}
var5_plot <- ggplot(s03, aes(x = SeriesInd, y = Var05)) +
  geom_point(color = "blue") +
  labs(title = "Plot of Var05 vs Series Index", x = "Series Index", y = "Value") +
  theme_minimal()
```

```{r}
var7_plot <- ggplot(s03, aes(x = SeriesInd, y = Var07)) +
  geom_point(color = "orange") +
  labs(title = "Plot of Var07 vs Series Index", x = "Series Index", y = "Value") +
  theme_minimal()
```

```{r}
grid.arrange(var5_plot, var7_plot, nrow = 2)
```

#Data Imputation 
I'm using linear imputation, so creating a line of best fit between the last two known points and filling in missing values along that line

```{r}
data_range <- which(s03$SeriesInd < 43022)
na_var5 <- which(is.na(s03$Var05[data_range]))
na_var7 <- which(is.na(s03$Var07[data_range]))
```

```{r}
imputed_var5 <- approx(x = s03$SeriesInd[data_range], y = s03$Var05[data_range], 
                              xout = s03$SeriesInd[data_range])$y
imputed_var7 <- approx(x = s03$SeriesInd[data_range], y = s03$Var07[data_range], 
                              xout = s03$SeriesInd[data_range])$y
```

```{r}
s03$Var05[data_range][na_var5] <- imputed_var5[na_var5]
s03$Var07[data_range][na_var7] <- imputed_var7[na_var7]
```

Values to forecast: 43022 - 43221
index numbers: 1623 - 1762

#Checking for Stationarity

```{r stationarity}
acf_var5 <- acf(s03$Var05[data_range], plot = FALSE)
acf_var7 <- acf(s03$Var07[data_range], plot = FALSE)

acf_var5_df <- data.frame(lag = acf_var5$lag, acf = acf_var5$acf)
acf_var7_df <- data.frame(lag = acf_var7$lag, acf = acf_var7$acf)

acf1 <- ggplot(acf_var5_df, aes(x = lag, y = acf)) +
  geom_bar(stat = "identity") +
  labs(title = "ACF of Var05", y = 'ACF')

acf2 <- ggplot(acf_var7_df, aes(x = lag, y = acf)) +
  geom_bar(stat = "identity") +
  labs(title = "ACF of Var07", y = 'ACF')

grid.arrange(acf1, acf2, nrow=2)
```

```{r pacf}
pacf_var5 <- pacf(s03$Var05[data_range], plot = FALSE)
pacf_var7 <- pacf(s03$Var07[data_range], plot = FALSE)

pacf_var5_df <- data.frame(lag = pacf_var5$lag, pacf = pacf_var5$acf)
pacf_var7_df <- data.frame(lag = pacf_var7$lag, pacf = pacf_var7$acf)

pacf1 <- ggplot(pacf_var5_df, aes(x = lag, y = pacf)) +
  geom_bar(stat = "identity") +
  labs(title = "PACF of Var05", y = 'Partial ACF')

pacf2 <- ggplot(pacf_var7_df, aes(x = lag, y = pacf)) +
  geom_bar(stat = "identity") +
  labs(title = "PACF of Var07", y = 'Partial ACF')

grid.arrange(pacf1, pacf2, nrow=2)
```
The data is non-stationary.
We will preforming differencing to make the data stationary.

```{r}
var5_diff <- diff(s03$Var05[data_range], differences = 1)
var7_diff <- diff(s03$Var07[data_range], differences = 1)

var5_diff_df <- data.frame(Index = seq_along(var5_diff), Value = var5_diff)
var7_diff_df <- data.frame(Index = seq_along(var7_diff), Value = var7_diff)
```

```{r}
var5_plot <- ggplot(var5_diff_df, aes(x = Index, y = Value)) +
  geom_point(color = "blue") +
  labs(title = "Plot of Var05 differenced vs Index", x = "Index", y = "Value") +
  theme_minimal()
```

```{r}
var7_plot <- ggplot(var7_diff_df, aes(x = Index, y = Value)) +
  geom_point(color = "blue") +
  labs(title = "Plot of Var07 differenced vs Index", x = "Index", y = "Value") +
  theme_minimal()
```

```{r}
grid.arrange(var5_plot, var7_plot, nrow = 2)
```
```{r stationarity_diff}
acf_var5 <- acf(var5_diff, plot = FALSE)
acf_var7 <- acf(var7_diff, plot = FALSE)

acf_var5_df <- data.frame(lag = acf_var5$lag, acf = acf_var5$acf)
acf_var7_df <- data.frame(lag = acf_var7$lag, acf = acf_var7$acf)

acf1 <- ggplot(acf_var5_df, aes(x = lag, y = acf)) +
  geom_bar(stat = "identity") +
  labs(title = "ACF of Var05", y = 'ACF')

acf2 <- ggplot(acf_var7_df, aes(x = lag, y = acf)) +
  geom_bar(stat = "identity") +
  labs(title = "ACF of Var07", y = 'ACF')

grid.arrange(acf1, acf2, nrow=2)
```

```{r pacf}
pacf_var5 <- pacf(var5_diff, plot = FALSE)
pacf_var7 <- pacf(var7_diff, plot = FALSE)

pacf_var5_df <- data.frame(lag = pacf_var5$lag, pacf = pacf_var5$acf)
pacf_var7_df <- data.frame(lag = pacf_var7$lag, pacf = pacf_var7$acf)

pacf1 <- ggplot(pacf_var5_df, aes(x = lag, y = pacf)) +
  geom_bar(stat = "identity") +
  labs(title = "PACF of Var05", y = 'Partial ACF')

pacf2 <- ggplot(pacf_var7_df, aes(x = lag, y = pacf)) +
  geom_bar(stat = "identity") +
  labs(title = "PACF of Var07", y = 'Partial ACF')

grid.arrange(pacf1, pacf2, nrow=2)
```

```{r}
fit_var5 <- auto.arima(var5_diff, stationary = TRUE)
summary(fit_var5)
```

```{r}
checkresiduals(fit_var5)
```

```{r}
fc_var5 <- forecast(fit_var5, h=100)
autoplot(fc_var5) + ylab('Var5 Differenced Forecast')
```

```{r}
fit <- Arima(var5_diff, order=c(2,1,3), include.constant=FALSE)
fc <- forecast(fit, h=100)
autoplot(fc) + ylab('Value')
```

```{r}
fit <- auto.arima(s03$Var05[data_range])
fc <- forecast(fit, h=100)
autoplot(fc) + ylab('Value')
```


```{r}
fit <- Arima(s03$Var05[data_range], order=c(2,1,3), include.drift=TRUE)
fc <- forecast(fit, h=100)
autoplot(fc) + ylab('Value')
```
